# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 374c90f1419db072b02801f6a42b6884fe983db27033a4418077770c337e73460d81c8588bf0d1f935b6865f1e22a60cdb17ac46e50605fe37f600b3cd928cf2

test:
  secret_key_base: c45ed965d1041fb2c0482d8e0cd06fcc12e6c177d1b72d5eabe691fb94ec9243ac5d42108672a7034d2cbd135eb6954e5b3b8993255a6c851a9acc6872f6d939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
